package Manager;


import java.awt.BorderLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author khaientiew
 */
public class managerMaintenance extends javax.swing.JFrame {
    private String loggedInEmail;

    /**
     * Creates new form Manager_Login
     */
    public managerMaintenance(String loggedInEmail) {
        this.loggedInEmail = loggedInEmail;
        initComponents();
        loadScheduler();
        Color col = new Color(224, 240, 255);
        Color buttonColor = new Color(228, 228, 228);
        Color color = new Color(242, 242, 242);
        getContentPane().setBackground(col);
        btnSales.setBackground(buttonColor);
        btnMaintenance.setBackground(buttonColor);
        btnMainMenu.setBackground(buttonColor);
        btnLogOut.setBackground(buttonColor);
        btnAssignScheduler.setBackground(buttonColor);
        btnEditStatus.setBackground(buttonColor);
        TbMaintenance.setBackground(color);
        BtnAll.setBackground(buttonColor);
        BtnIP.setBackground(buttonColor);
        BtnDone.setBackground(buttonColor);
        BtnClosed.setBackground(buttonColor);
        BtnCancelled.setBackground(buttonColor);
        BtnOpen.setBackground(buttonColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void buttonClick(String type) {
        managerMaintenanceClass manager = new managerMaintenanceClass();
        ArrayList<String[]> filteredBookings = manager.filterIssue(type);
        loadTable(filteredBookings);
    }
    
    private void loadTable(ArrayList<String[]> issues) {
        DefaultTableModel model = (DefaultTableModel) TbMaintenance.getModel();
        model.setRowCount(0);
        
        for (String[] issue : issues) {
            model.addRow(issue);
        }
    }
    
    private void loadScheduler(){
        CBSchedular.removeAllItems();
        
        File file = new File("users.txt");
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] userDetails = line.split(";");
                String name = userDetails[0];
                String role = userDetails[6];
                
                System.out.println("Scheduler: " + name);

                // Check if the role is "scheduler"
                if (role.equalsIgnoreCase("scheduler")) {
                    CBSchedular.addItem(name);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCompanyName = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblMaintenanceList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbMaintenance = new javax.swing.JTable();
        btnAssignScheduler = new javax.swing.JButton();
        btnEditStatus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnMainMenu = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnMaintenance = new javax.swing.JButton();
        CBStatus = new javax.swing.JComboBox<>();
        CBSchedular = new javax.swing.JComboBox<>();
        BtnAll = new javax.swing.JButton();
        BtnIP = new javax.swing.JButton();
        BtnDone = new javax.swing.JButton();
        BtnClosed = new javax.swing.JButton();
        BtnCancelled = new javax.swing.JButton();
        BtnOpen = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyName.setFont(new java.awt.Font("Bradley Hand", 0, 36)); // NOI18N
        lblCompanyName.setText("Hall Symphony Inc.");
        lblCompanyName.setLocation(new java.awt.Point(0, 25));

        btnLogOut.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblMaintenanceList.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        lblMaintenanceList.setText("Maintenance Operations List");

        TbMaintenance.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        TbMaintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ticket ID", "HallID", "Date/Time", "Issue", "Status", "Scheduler"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TbMaintenance);

        btnAssignScheduler.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnAssignScheduler.setText("Assign Scheduler");
        btnAssignScheduler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignSchedulerActionPerformed(evt);
            }
        });

        btnEditStatus.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnEditStatus.setText("Edit Status");
        btnEditStatus.setSize(new java.awt.Dimension(78, 21));
        btnEditStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStatusActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setPreferredSize(new java.awt.Dimension(80, 23));
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnSales.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnSales.setText("Sales Dashboard");
        btnSales.setPreferredSize(new java.awt.Dimension(80, 23));
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });

        btnMaintenance.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        btnMaintenance.setText("Maintenance Operations");
        btnMaintenance.setPreferredSize(new java.awt.Dimension(80, 23));
        btnMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Done", "Closed", "Cancelled", " " }));

        CBSchedular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSchedularActionPerformed(evt);
            }
        });

        BtnAll.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnAll.setText("All");
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });

        BtnIP.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnIP.setText("In Progress");
        BtnIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIPActionPerformed(evt);
            }
        });

        BtnDone.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnDone.setText("Done");
        BtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoneActionPerformed(evt);
            }
        });

        BtnClosed.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnClosed.setText("Closed");
        BtnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClosedActionPerformed(evt);
            }
        });

        BtnCancelled.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnCancelled.setText("Cancelled");
        BtnCancelled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelledActionPerformed(evt);
            }
        });

        BtnOpen.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        BtnOpen.setText("Open");
        BtnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompanyName)
                        .addGap(449, 449, 449))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaintenanceList))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditStatus)
                                        .addContainerGap(240, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(CBSchedular, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAssignScheduler)
                                        .addGap(177, 177, 177))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLogOut)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnOpen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnIP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnDone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnClosed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCancelled)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyName)
                    .addComponent(btnLogOut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAll)
                    .addComponent(BtnIP)
                    .addComponent(BtnDone)
                    .addComponent(BtnClosed)
                    .addComponent(BtnCancelled)
                    .addComponent(BtnOpen)
                    .addComponent(lblMaintenanceList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditStatus))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBSchedular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignScheduler)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        this.dispose();
        new managerMainMenu(loggedInEmail).setVisible(true);
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        this.dispose();
        new managerSales(loggedInEmail).setVisible(true);
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceActionPerformed
        this.dispose();
        new managerMaintenance(loggedInEmail).setVisible(true);
    }//GEN-LAST:event_btnMaintenanceActionPerformed

    private void btnAssignSchedulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignSchedulerActionPerformed
        // TODO add your handling code here:
        int selectedRow = TbMaintenance.getSelectedRow();  // Get the selected row from the table
        if (selectedRow != -1) {
            String selectedStatus = "InProgress";  // Get the selected status from the comboBox
            String id = TbMaintenance.getValueAt(selectedRow, 0).toString();  // Get the ID of the selected row
            String selectedScheduler = CBSchedular.getSelectedItem().toString();
            
            // Now update the status in the file
            File file = new File("issue.txt"); 
            List<String> lines = new ArrayList<>();
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] splitLine = line.split(";"); 
                    if (splitLine[0].equals(id)) {
                        splitLine[4] = selectedStatus;
                        splitLine[5] = selectedScheduler;
                    }
                    lines.add(String.join(";", splitLine));  // Reconstruct the line
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // Write the updated lines back to the file
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
                for (String line : lines) {
                    writer.write(line);
                    writer.newLine();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // Update the table to reflect the changes
            TbMaintenance.setValueAt(selectedStatus, selectedRow, 2);
            TbMaintenance.setValueAt(selectedScheduler, selectedRow, 5);
            JOptionPane.showMessageDialog(null, "Status and Scheduler updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to update.");
        }
    }//GEN-LAST:event_btnAssignSchedulerActionPerformed

    private void btnEditStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = TbMaintenance.getSelectedRow();  // Get the selected row from the table
        if (selectedRow != -1) {
            String selectedStatus = CBStatus.getSelectedItem().toString();  // Get the selected status from the comboBox
            String id = TbMaintenance.getValueAt(selectedRow, 0).toString();  // Get the ID of the selected row
            
            // Now update the status in the file
            File file = new File("issue.txt"); 
            List<String> lines = new ArrayList<>();
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] splitLine = line.split(";"); 
                    if (splitLine[0].equals(id)) {
                        splitLine[4] = selectedStatus;  // Update the status
                    }
                    lines.add(String.join(";", splitLine));  // Reconstruct the line
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // Write the updated lines back to the file
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
                for (String line : lines) {
                    writer.write(line);
                    writer.newLine();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            // Update the table to reflect the changes
            TbMaintenance.setValueAt(selectedStatus, selectedRow, 2);
            JOptionPane.showMessageDialog(null, "Status updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to update.");
        }
    }//GEN-LAST:event_btnEditStatusActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login.LoginPage().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        // TODO add your handling code here:
        managerMaintenanceClass manager = new managerMaintenanceClass();
        ArrayList<String[]> IssueList = manager.readIssues();
        loadTable(IssueList);
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIPActionPerformed
        // TODO add your handling code here:
        buttonClick("InProgress");
    }//GEN-LAST:event_BtnIPActionPerformed

    private void BtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoneActionPerformed
        // TODO add your handling code here:
        buttonClick("Done");
    }//GEN-LAST:event_BtnDoneActionPerformed

    private void BtnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClosedActionPerformed
        // TODO add your handling code here:
        buttonClick("Closed");
    }//GEN-LAST:event_BtnClosedActionPerformed

    private void BtnCancelledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelledActionPerformed
        // TODO add your handling code here:
        buttonClick("Cancelled");
    }//GEN-LAST:event_BtnCancelledActionPerformed

    private void CBSchedularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSchedularActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_CBSchedularActionPerformed

    private void BtnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpenActionPerformed
        // TODO add your handling code here:
        buttonClick("Open");
    }//GEN-LAST:event_BtnOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    


    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAll;
    private javax.swing.JButton BtnCancelled;
    private javax.swing.JButton BtnClosed;
    private javax.swing.JButton BtnDone;
    private javax.swing.JButton BtnIP;
    private javax.swing.JButton BtnOpen;
    private javax.swing.JComboBox<String> CBSchedular;
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JTable TbMaintenance;
    private javax.swing.JButton btnAssignScheduler;
    private javax.swing.JButton btnEditStatus;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnMaintenance;
    private javax.swing.JButton btnSales;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblMaintenanceList;
    // End of variables declaration//GEN-END:variables
}
