/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scheduler;

import Customer.hallClass;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Huawei
 */
public class schedulerAddHall extends javax.swing.JFrame {
    private final String loggedInEmail;
    private boolean isComboBoxReadyForSelection = false;
    /**
     * Creates new form schedulerAddHall
     * @param loggedInEmail
     */
    public schedulerAddHall(String loggedInEmail) {
        this.loggedInEmail = loggedInEmail;
        initComponents();
        populateComBoxHallType();
    }

    private void handleHallTypeSelection() {
        // Check if the comboBox is ready for user selection
        if (!isComboBoxReadyForSelection) {
            return; // Exit the method if not ready
        }

        // Retrieve the selected item
        String hallType = (String) comBoxHallType.getSelectedItem();

        // Check if hallType is null
        if (hallType == null) {
            // Handle the null case (e.g., log, show an error, or return)
            System.err.println("No hall type selected!");
            return; // Exit the method if hallType is null
        }

        char hallPrefix = '\0';

        switch (hallType) {
            case "Auditorium" -> hallPrefix = 'A';
            case "Banquet Hall" -> hallPrefix = 'B';
            case "Meeting Room" -> hallPrefix = 'M';
            default -> {
                // Handle unexpected hall types, if needed
                System.err.println("Unknown hall type: " + hallType);
                return;
            }
        }

        hallClass hall = new hallClass();
        String result = hall.getLastHallTypeID(hallPrefix);

        lblAddHallID.setText(result);

        // Populate capacity and price fields based on the hall type
        switch (hallType) {
            case "Auditorium" -> {
                txtAddCapacity.setText("1000");
                txtAddPrice.setText("300");
            }
            case "Banquet Hall" -> {
                txtAddCapacity.setText("300");
                txtAddPrice.setText("100");
            }
            case "Meeting Room" -> {
                txtAddCapacity.setText("30");
                txtAddPrice.setText("50");
            }
        }
    }

    private void populateComBoxHallType() {
        String[] hallTypes = {"Auditorium", "Banquet Hall", "Meeting Room"};

        // Remove any existing items
        comBoxHallType.removeAllItems();

        // Temporarily disable selection handling
        isComboBoxReadyForSelection = false;

        // Add each hall type to the combo box
        for (String hallType : hallTypes) {
            comBoxHallType.addItem(hallType);
        }

        // Enable selection handling after population is complete
        isComboBoxReadyForSelection = true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddCapacity = new javax.swing.JTextField();
        txtAddPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        comBoxHallType = new javax.swing.JComboBox<>();
        lblAddHallID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setText("Add Hall");

        jLabel2.setText("Hall ID");

        jLabel3.setText("Hall Type");

        jLabel4.setText("Capacity");

        jLabel5.setText("Price (RM/per hour)");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        comBoxHallType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comBoxHallType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxHallTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddCapacity)
                                    .addComponent(txtAddPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(comBoxHallType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAddHallID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAdd)
                        .addGap(53, 53, 53)
                        .addComponent(btnCancel)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comBoxHallType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAddHallID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();

        schedulerHallManagement scheduler = new schedulerHallManagement(loggedInEmail);
        scheduler.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String hallID = lblAddHallID.getText();
        String hallType = (String) comBoxHallType.getSelectedItem();
        String capacityStr = txtAddCapacity.getText();
        String priceStr = txtAddPrice.getText();
        Date bookingDate = null;
        Date startTime = null;
        Date endTime = null;
        String availability = "Available";

        // Field authentication
        if (hallID.isEmpty() || hallType.isEmpty() || capacityStr.isEmpty() || priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert string to int
        int capacity = Integer.parseInt(capacityStr);
        Double price = Double.valueOf(priceStr);

        hallClass hall = new hallClass(hallID, hallType, price, bookingDate, startTime, endTime, capacity, availability);
        String result = hall.addHall(hallID, hallType, price, bookingDate, startTime, endTime, capacity, availability);

        // Display results of adding hall
        if (result.equals("success")) {
            JOptionPane.showMessageDialog(this, "Hall details successfully added!");
        } else {
            JOptionPane.showMessageDialog(this, "Error saving the data. Please try again.", "File Error", JOptionPane.ERROR_MESSAGE);
        }

        // Close the current window
        this.dispose();

        // Create a new scheduler management window
        schedulerHallManagement scheduler = new schedulerHallManagement(loggedInEmail);
        scheduler.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void comBoxHallTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxHallTypeActionPerformed
        handleHallTypeSelection();
    }//GEN-LAST:event_comBoxHallTypeActionPerformed

        
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> comBoxHallType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAddHallID;
    private javax.swing.JTextField txtAddCapacity;
    private javax.swing.JTextField txtAddPrice;
    // End of variables declaration//GEN-END:variables
}
